In [1]:
from gensim.models import KeyedVectors
import os, sys, json, numpy as np

from funcs import utils

In [3]:
proj_root = utils.find_project_root()
MODEL_PATH = proj_root / "models" / "bioconceptvec" / "bioconceptvec_word2vec_skipgram.bin"
assert MODEL_PATH.exists()

In [4]:
embeddings = KeyedVectors.load_word2vec_format(str(MODEL_PATH), binary=True)

## embeddings

In [15]:
concept_vec = embeddings["Gene_2997"]
print(concept_vec.shape)
concept_vec

(100,)


array([-0.01676855,  0.56551105,  1.00418   ,  0.13895853,  0.0487967 ,
        0.167735  , -0.07339028,  0.4984045 , -0.18709421, -0.07556584,
       -0.2731313 , -0.4116881 ,  0.089853  ,  0.48193076, -0.257556  ,
       -0.46385273,  0.21456282,  0.4653187 ,  0.54888815,  0.24953978,
        0.12102792,  0.16346483, -0.21817666,  0.17584416,  0.00181668,
        0.06124614, -0.665759  ,  0.27698943, -0.34381142, -0.29450157,
       -0.04999237, -0.42160794,  0.587909  ,  0.04599308, -0.52086115,
       -0.3301775 , -0.4439534 , -0.07623559,  1.1971241 , -0.05919534,
       -0.3013499 , -0.32670468, -0.69612557, -0.1875824 , -0.27888337,
        0.21057817,  0.1439918 , -0.5378452 ,  0.24323015, -0.19288874,
       -0.26549867,  0.57281816, -0.5705898 , -0.07732881,  0.39814204,
        0.5079281 ,  0.01936658,  0.78174835, -0.42671528, -0.10127745,
        0.7548943 ,  0.2102662 ,  0.10312578,  0.16521394,  0.10868917,
       -1.3835231 ,  0.6732168 , -0.22165756,  0.17197599, -0.63

In [24]:
concept_vec = embeddings["obesity"]
print(concept_vec.shape)
concept_vec

(100,)


array([-3.71083796e-01,  1.07148850e+00,  3.05091262e-01,  5.10576785e-01,
        2.66760796e-01,  3.51097733e-01,  1.40599117e-01,  8.96661654e-02,
        1.86773874e-02,  3.79347056e-01, -4.68960762e-01, -1.37693048e-01,
        1.77459598e-01, -1.60546005e-01, -3.39218050e-01, -6.12643473e-02,
       -3.06290612e-02,  1.49603084e-01,  5.15843809e-01,  1.45216823e-01,
       -3.11469257e-01,  8.77281502e-02, -3.56156006e-03,  2.76672423e-01,
       -6.98156580e-02,  4.00094360e-01,  3.79867882e-01, -1.14888370e-01,
       -5.37738442e-01,  6.35682642e-02,  2.28840768e-01,  7.53096417e-02,
        7.48957694e-01, -1.60261169e-01, -4.71208990e-03, -2.79527843e-01,
       -7.63943642e-02,  8.23164359e-02,  1.55679569e-01, -4.57895279e-01,
       -2.38522694e-01, -5.56444982e-04,  9.15566809e-04, -1.50853187e-01,
        6.01500943e-02, -1.50952846e-01, -6.01965129e-01, -5.78949928e-01,
        3.54220904e-02,  5.82978129e-01,  1.40002877e-01,  3.13111752e-01,
        4.44254279e-02, -

In [21]:
embeddings.similar_by_word("Chemical_MESH_D010710")

[('phosphorous', 0.7894465327262878),
 ('Chemical_MESH_D010758', 0.7885470986366272),
 ('Chemical_MESH_D008274', 0.7815420627593994),
 ('Chemical_MESH_D010757', 0.7814880013465881),
 ('Chemical_MESH_C102006', 0.7811864614486694),
 ('inorganic', 0.7791789770126343),
 ('po4', 0.7526918649673462),
 ('polyphosphate', 0.7526358962059021),
 ('-inorganic', 0.7481254935264587),
 ('phosphate', 0.7417328357696533)]

## vocab

In [6]:
dir(embeddings)

['__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_adapt_by_suffix',
 '_load_specials',
 '_log_evaluate_word_analogies',
 '_save_specials',
 '_smart_save',
 '_upconvert_old_d2vkv',
 '_upconvert_old_vocab',
 'add_lifecycle_event',
 'add_vector',
 'add_vectors',
 'allocate_vecattrs',
 'closer_than',
 'cosine_similarities',
 'distance',
 'distances',
 'doesnt_match',
 'evaluate_word_analogies',
 'evaluate_word_pairs',
 'expandos',
 'fill_norms',
 'get_index',
 'get_normed_vectors',
 'get_vecattr',
 'get_vector',
 'has_index_for',
 'index2entity',
 'index2word',
 'index_to_key',
 'init_sims',
 'intersect_word2vec_

In [16]:
words = list(embeddings.key_to_index.keys())

In [19]:
vocab_path = MODEL_PATH.parent / "bioconceptvec_word2vec_skipgram.vocab.txt"
with vocab_path.open("w") as f:
    for _ in words:
        f.write(_+"\n")

## misc

In [23]:
concept_vec = embeddings["Disease_MESH_D001177"]
print(concept_vec.shape)
concept_vec

(100,)


array([ 0.2960074 ,  0.6256516 ,  0.2670746 ,  0.34807175, -0.04165087,
       -0.09752116, -0.40541244,  0.25948277,  0.07092364,  0.0350636 ,
       -0.64950913, -0.2906432 , -0.05058294,  0.69056505,  0.04398592,
        0.00928383, -0.5560358 ,  0.3570897 ,  0.1035601 ,  0.3552391 ,
       -0.36545876,  0.26320136, -0.14704889, -0.20038943,  0.03579602,
       -0.04495963, -0.58139443,  0.33308178, -0.32946816,  0.0204215 ,
       -0.06386555, -0.8316091 ,  1.1119683 , -0.10233486, -0.6018919 ,
       -0.6721442 ,  0.08029539,  0.49111655,  0.20853408, -0.30212963,
        0.20978005,  0.4475316 ,  0.13602822,  0.09381495,  0.07188424,
        0.5755963 , -1.190664  ,  0.03908456, -0.06297127,  0.09664495,
       -0.28475788,  0.14751416,  0.21707968, -0.02053396,  0.1699593 ,
       -0.0335967 , -0.7081233 ,  0.576206  ,  0.68854976,  0.03009125,
       -0.25835446, -0.5964552 , -0.05077269,  0.28730497,  0.26410562,
       -0.9650466 ,  0.04805272, -0.18496643,  0.01776952,  0.46